sudo: required

services:
  - docker

before_install: 
  - docker build -t charlesonunze/react-with-docker -f Dockerfile.dev .

script: 
  - docker run -e CI=true charlesonunze/react-with-docker yarn run test -- --coverage