sudo: required

services:
  - docker

before_install: 
  - docker build -f Dockerfile.dev -t charlesonunze/react-with-docker .

script: 
  - docker run charlesonunze/react-with-docker npm run test -- --coverage