# Use the official image as a parent image.
FROM node:12-alpine

# Set the working directory.
WORKDIR /react-app

# Copy the file from your host to your current location.
COPY package.json .

# Run the command inside your image filesystem.
RUN yarn install

# Copy the rest of your app's source code from your host to your image filesystem.
COPY . .

# Run the specified command within the container.
CMD [ "yarn", "start" ]